# Generated by Django 5.1.2 on 2024-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0002_cake_customer_cakecustomization_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakecustomization',
            name='egg_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cakecustomization',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cakecustomization',
            name='shape',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cakecustomization',
            name='toppings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cakecustomization',
            unique_together={('cake', 'customer')},
        ),
    ]
