# Generated by Django 5.1.2 on 2024-10-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetspot_app', '0004_delete_user_alter_cake_image_alter_cake_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cake_customization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sweetspot_app.cakecustomization'),
        ),
    ]
